apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: zj43fuier-python 
  janus-idp.io/tekton: zj43fuier-python
  backstage.io/kubernetes-id: zj43fuier-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zj43fuier-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml