apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: zj43fuier-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zj43fuier-python 
  name: zj43fuier-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: zj43fuier-python 
